language: python
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - env: TOXENV=pylint
        - env: TOXENV=flake
        - env: TOXENV=pydocstyle
        - env: TOXENV=coverage
services:
    - postgresql
install:
    - pip install -r requirements_dev.txt
before_script:
    - psql -c 'CREATE ROLE product_aggregator WITH LOGIN;' -U postgres
    - psql -c 'ALTER USER product_aggregator CREATEDB;' -U postgres
script:
    - tox
