# Generated by Django 3.0.8 on 2020-07-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200708_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='price',
        ),
    ]
